[package]
name = "kernels"
version = "0.1.0"
edition = "2021"

[dependencies]
dummy-alloc = "0.1.0"
ndarray = { version = "0.16.1", default-features = false }
num = { version = "0.4", default-features = false }

[lib]
name = "kernels"
path = "src/lib.rs"
crate-type = ["cdylib"]
